### ISSUE TITLE
Add CodeCoverage

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-approval#10]
Add CodeCov to measure and report the test coverage.

**Comment by KabacinskiPiotr** [comment]
I cannot add an application to OSCM organization. I am authorized only to specific repositories:

If someone has access to the settings on the main GitHub OSCM page, please grant permissions / add an application
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/18506c5c-0eb2-4baa-b617-109bd63da4bd)

https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/reviewing-your-organizations-installed-integrations
