### ISSUE TITLE
Embed badges for travis and CodeCov

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-approval#27]
Display the Travis CI Build status and code coverage result in README.md. E.g. see oscm-app.
[![Build status](https://travis-ci.org/servicecatalog/oscm-approval.svg?branch=master)](https://travis-ci.org/servicecatalog/oscm-approval)
[![codecov](https://codecov.io/gh/servicecatalog/oscm-approval/branch/master/graph/badge.svg)](https://codecov.io/gh/servicecatalog/oscm-approval)

**Comment by KabacinskiPiotr** [comment]
![image](https://user-images.githubusercontent.com/59691196/91838413-bd40d100-ec4d-11ea-938e-4075baa5dee6.png)

**Comment by GoebelL** [comment]
@KabacinskiPiotr 
The badges are commonly aligned above of the readme heading. Please adjust properly, to have a unique appearance like the other repos, f.e. https://github.com/servicecatalog/oscm-rest-api
