### ISSUE TITLE
Sample data for approval process

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-approval#46]
**Summary**
Enhance sample data setup to provide a ready-to-use configuration for using a subscription approval process.

**Details**
Via SQL dump or respective scripting
- Preconfigure trigger process in the sample data customer organization (suspending subscribe to service trigger, NotificationSerivce endpoint URL etc.)

- Create supplier own marketplace for self-offering services and restrict it for the supplier organization (to keep it internal -> not accessible for the customers)  
- Import technical service for the approval tool in the supplier organization
- Create a free marketable service offer for the approval tool and publish it on said supplier marketplace    
- Configure approver and connection data in custom attributes of supplier account

**Acceptance criteria**
After setup with sample data
- [ ] Supplier marketplace is accessible and shows the approval tool service as only service
- [ ] As supplier the approval tool can be subscribed out of the box
- [ ] The customer can subscribe with approval trigger
- [ ] The approver can approve the tasks created by the customer 
  
**Additional context**
N/A

**Comment by cworf91** [comment]
https://github.com/servicecatalog/oscm-dockerbuild/pull/285
