### ISSUE TITLE
Test manual deployment and usage

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-approval#5]
See https://github.com/servicecatalog/oscm-approval/blob/master/README.md.

**Comment by KabacinskiPiotr** [comment]
I've made some minor changes to the manual. 
Approve, Reject, adding comments works. Information about creating a new approve is sent to e-mail
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/fdd425cc-be85-4ee1-b8f1-07913c26c4d2)
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/bad66867-f218-4697-82a4-d850d96eec3e)
![image.png](https://images.zenhubusercontent.com/5e1c60ee5e668415ca9f76d9/5f8e9411-686d-4335-bcb2-26a84948d7ce)
