### ISSUE TITLE
Add Travis

### ISSUE THREAD

**Issue by GoebelL** [servicecatalog/oscm-approval#9]
Add Travis integration to compile, package and test the modules.

**Comment by cworf91** [comment]
The Travis file is checked in. Unfortunately, you have to be an organization administrator to activate travis. Therefore, the task has do be done from someone with the administrator privileges

**Comment by KabacinskiPiotr** [comment]
![image](https://user-images.githubusercontent.com/59691196/91725216-b5762380-eb9e-11ea-84e8-a3e51fe09076.png)
